### ISSUE TITLE
How to render example

### ISSUE THREAD

**Issue by bitmapdata** [Asana/typed-react#39]
I wonder How to render the sample code.

I tried to following. but have not appeared.

``` ts
//main.ts

import React = require("react");
import TypedReact = require("typed-react");

export interface TimerProps {
    tickInterval: number;
}

interface TimerState {
    ticksElapsed: number;
}

class Timer extends TypedReact.Component<TimerProps, TimerState> {
    private interval: number;

    getInitialState() {
        return {
            ticksElapsed: 0
        };
    }

    tick() {
        this.setState({
            ticksElapsed: this.state.ticksElapsed + 1
        });
    }

    componentDidMount() {
        this.interval = setInterval(this.tick, this.props.tickInterval);
    }

    componentWillUnmount() {
        clearInterval(this.interval);
    }

    render() {
        return React.DOM.div(null, "Ticks Elapsed: ", this.state.ticksElapsed);
    }
}

var timer = TypedReact.createClass(Timer);

React.render(
    React.createElement(timer, null),
    document.body
);
```

**Comment by Ciantic** [comment]
I tried to figure out this for half an hour too. You should mention this somewhere.

**Comment by barong** [comment]
Hi, can anybody share a working example please? 
I'm trying to run example code from README file with requirejs, but I don't understand what exactly what shall will be compiled finally.
My result code looks like this - 
define(["require", "exports", "react", "typed-react"], function (require, exports, React, TypedReact) {...}
And when I run application I get error - typed-react.js Not Found.
Can anybody help me with it?

**Comment by pspeter3** [comment]
@barong We don't explicitly support requirejs and encourage commonjs or es6 modules.
