### ISSUE TITLE
How to use the production version of react? (no log messages etc.)

### ISSUE THREAD

**Issue by duncanawoods** [Asana/typed-react#41]
If I browserify compiled typescript that uses typed-react, the version of react that is included is the debug version which is a slower due to extra verification checks and log messages.

Is there a way to deploy with the production version?

**Comment by jnetterf** [comment]
While bundling it, you'll want to set the environment variable `NODE_ENV` to `production`. One way to do that is by specifying `NODE_ENV=production` before the command that you run to bundle your application. For example, if you're using browserify from the shell, you would run `NODE_ENV=production browserify ...`. This also works for webpack, or build systems that use browserify or webpack. Bundling it in production mode causes things like `process.env.NODE_ENV !== 'production'` inside of React to be replaced with `false`.

If the end goal is a web application, you should then pipe the output through something like [uglify](https://github.com/mishoo/UglifyJS) to perform dead-code removal.

**Comment by duncanawoods** [comment]
Using grunt-env to set this flag looks like it has done the trick. Thanks!

**Comment by pspeter3** [comment]
Thanks @jnetterf
