### ISSUE TITLE
React v0.13 support

### ISSUE THREAD

**Issue by robertknight** [Asana/typed-react#45]
The README was updated to mention that the purpose of typed-react is going to change with React v0.13 to provide support for features like mixins with ES6-style classes.

Do you have any more details on how you envisage this working? Would it be along the lines of https://github.com/brigand/react-mixin ?

It seems that discussion upstream about how best to combine ES6 classes and mixins is still very much in-flight (eg. https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750 ). I'm not super-convinced about that direction though as it would result in a lot of unnecessary nesting in the resulting component tree.

**Comment by pspeter3** [comment]
I think that likely TypedReact during 0.13 would be supporting mixins natively for ES6. FWIW, we use a fair amount of "higher order" components at Asana.

**Comment by robertknight** [comment]
Can this be pushed to an npm release?

**Comment by pspeter3** [comment]
This should be pushed now.
