### ISSUE TITLE
extractPrototype() executes get properties

### ISSUE THREAD

**Issue by duncanawoods** [Asana/typed-react#49]
If a Typed.Component defines get/set property methods, all the get methods are executed during view initialization when the prototype is copied e.g.

    var TestObject = (function () {
        function TestObject() {
            this.str = "test string";
        }
        Object.defineProperty(TestObject.prototype, "TestProperty", {
            get: function () {
                console.log("exec get");
                return this.str;
            },
            set: function (value) {
                console.log("exec set");
                this.str = value;
            },
            enumerable: true,
            configurable: true
        });
        return TestObject;
    })();

    function extractPrototype(clazz) {
        var proto = {};
        for (var key in clazz.prototype) {
            proto[key] = clazz.prototype[key];
        }
        return proto;
    }
    var extracted = extractPrototype(TestObject);

This will print "exec get" when extractPrototype accesses TestObject.prototype["TestProperty"]. Are there any quick fixes to avoid executing get methods during the extract?

**Comment by duncanawoods** [comment]
I have experimented with a fix:

    function extractPrototype(clazz) {
        var proto = {};
        for (var key in clazz.prototype) {
            if (ILLEGAL_KEYS[key] === undefined) {
                var getter = clazz.prototype.__lookupGetter__(key);
                var setter = clazz.prototype.__lookupSetter__(key);
       
                if ( getter || setter ) {
                    Object.defineProperty(proto, key, Object.getOwnPropertyDescriptor(clazz.prototype, key));
                }
                else {
                    proto[key] = clazz.prototype[key];
                } 
            }
        }
        return proto;
    }

But it looks likes properties cause other problems further into react during mixSpecIntoComponent.

**Comment by pspeter3** [comment]
Yeah, I think the properties are a bit strange. We can fix it if React supports it but it sounds like they don't so I would like not to support it. Does that sound reasonable?

I'm going to close this for now. Please feel free to reopen if you disagree.

**Comment by duncanawoods** [comment]
Yep - closing is good.

The only change I might suggest is a warning if properties are defined because their evaluated values are copied to the prototype which causes confusing results. It would be better to skip them completely rather than the borked copy. If you would like that then I can put together a pull request.

Using properties is probably rare for JS guys but common for those coming form C#.
