### ISSUE TITLE
Feature Request: Track state automatically

### ISSUE THREAD

**Issue by basarat** [Asana/typed-react#56]
Would be great if in React 0.13 when using classes we provide a utility function `TypedReact.track(this)` that will allow us to rewrite the following component: 

```ts
export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }
  tick() {
    this.setState({count: this.state.count + 1});
  }
  render() {
    return (
      <div onClick={this.tick.bind(this)}>
        Clicks: {this.state.count}
      </div>
    );
  }
}
```

into this: 

```ts
export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};

    // Call after `this.state` is set
    TypedReact.track(this);
  }
  tick() {
    // An easier (and more type safe) way to update state
    this.state.count = this.state.count + 1;
  }
  render() {
    return (
      <div onClick={this.tick.bind(this)}>
        Clicks: {this.state.count}
      </div>
    );
  }
}
```

Or do you feel it belongs in a new project?

# References 
* Class docs : http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes
* `ko.track` function in knockout that is inspiring this: http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/

**Comment by jnetterf** [comment]
If you just want updates one level deep, you can just use `Object.observe`. Try adding this to your constructor:
```
Object.observe(this.state, () => this.forceUpdate());
```

A few notes:

 - Browser support is [poor](http://kangax.github.io/compat-table/es7/#Object.observe). You should use a [polyfill](https://github.com/MaxArt2501/object-observe).
 - The polyfill is not very efficient (it polls!)
 - This doesn't make for very idiomatic code. Doing this would make your code less approachable for people who are used to `setState`. The React developers [strongly recommend](https://facebook.github.io/react/docs/component-api.html) you treat state as if it were immutable.

**Comment by basarat** [comment]
My ideas are therefore ill advised, I'll investigate more. Thanks for clearing that up :rose:

**Comment by jnetterf** [comment]
I don't want to come across as negative! It's a nicer syntax, and I would use it were there a way of avoiding those disadvantages.
